.\" gf man page
.TH gf 1 "May 2016" Linux "User Manuals"
.SH NAME
gf (v0.1) \- finds what you are looking for 
.SH SYNOPSIS
.B gf
.RI [ OPTIONS ] 
PATTERN 
.br
.B gf 
.RI [ OPTIONS ]
.RB [ \-i
.IR FILE ]
PATTERN
.
.SH DESCRIPTION
.B gf
is a tool which will search for the given
.IR TERM 
in the file system below the current directory. 
.B gf 
also has the option to ignore files with the proper flags.
.
.SH OPTIONS
.SH FILES
.SH AUTHOR
Julio de Leon <jangelod@gmail.com>

