#!/usr/bin/env perl
use warnings;
use strict;
use JSON;
use JSON::XS;
while(<>){
  chomp;
#  next if $_ =~ /.+GUID.+/;
  next if not ($_ =~ /.+hotel.+/i);
  next if not ($_ =~ /.+flight.+/i);
  my $jsonL = JSON->new->allow_nonref;
  my $perl_scalar = $jsonL->decode($_);
  print $jsonL->pretty->encode($perl_scalar);
}
