syntax enable
set number
set history=100
set ttyfast
set shortmess+=I
set smartindent
set expandtab
set softtabstop=2
set shiftwidth=2
set incsearch
set hlsearch
set cursorline
set showmatch
set matchtime=3
set wildmenu
set scrolloff=10
set sidescrolloff=5
set gdefault
set backspace=indent,eol,start
set showtabline=2
set ignorecase
set smartcase
set showbreak=↪
set synmaxcol=300
